import Head from "next/head";
import { useEffect, useState } from "react";
import Banner from "../components/Banner";
import Navbar from "../components/Navbar";
import List from "../components/List";
import newPopularRequests from "../newPopularRequest";
import { movieC, popularC, tvC } from "../redux/slices/navbarSlice";
import { useDispatch } from "react-redux";

export async function getServerSideProps(context) {
    const [
        playingMo,
        popularMo,
        popularTv,
        upcomMo,
        airTv,
        airTod,
        topMo,
        topTv,
    ] = await Promise.all([
        fetch(newPopularRequests.fetchNowPlayingMovies).then((res) => res.json()),
        fetch(newPopularRequests.fetchPopularMovies).then((res) => res.json()),
        fetch(newPopularRequests.fetchPopularTvShows).then((res) => res.json()),
        fetch(newPopularRequests.fetchUpcomingMovies).then((res) => res.json()),
        fetch(newPopularRequests.fetchTvShowsOnTheAir).then((res) => res.json()),
        fetch(newPopularRequests.fetchTvShowsAiringToday).then((res) => res.json()),
        fetch(newPopularRequests.fetchTopRatedMovies).then((res) => res.json()),
        fetch(newPopularRequests.fetchTopRatedTvShows).then((res) => res.json()),
    ]);
    
    return {
        props: {
            playingMo,
            popularMo,
            popularTv,
            upcomMo,
            airTv,
            airTod,
            topMo,
            topTv,

        }, // will be passed to the page component as props
    };
}

export default function Home({
    playingMo,
    popularMo,
    popularTv,
    upcomMo,
    airTv,
    airTod,
    topMo,
    topTv,
}) {

    const dispatch = useDispatch();
    useEffect(() => {
        dispatch(movieC(false));
        dispatch(tvC(false));
        dispatch(popularC(true));
    }, [dispatch])

    return (
        <>
            <Head>
                <title>Netflix</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/netflixSymbol.svg" />
            </Head>

            <div className="text-white">
                <Navbar />
                <Banner movies={playingMo.results} />
                <div className="pb-10">
                    <List name="Playing Movies" list={playingMo.results} tp="movie" />
                    <List name="Popular Movies" list={popularMo.results} tp="movie" />
                    <List name="Popular Tv Shows" list={popularTv.results} />
                    <List name="Upcoming Movies" list={upcomMo.results} tp="movie" />
                    <List name="Tv shows on the air" list={airTv.results} tp="tv" />
                    <List name="Tv shows airing today" list={airTod.results} tp="tv" />
                    <List name="Top Rated Movies" list={topMo.results} tp="movie" />
                    <List name="Top Rated Tv Shows" list={topTv.results} tp="tv" />
                </div>
            </div>
        </>
    );
}
