import React from 'react';
import { useSelector } from 'react-redux';
import { selectItem, selectType } from '../redux/slices/previewSlice';
import BLogo from "../components/BLogo";
import Cast from '../components/Cast';
import Testimonials from '../components/Testimonials';
import Head from 'next/head';
export default function Preview() {

    const item = useSelector(selectItem);
    const type = useSelector(selectType);
    
    return (

        <div className="text-white"
        >
            <Head>
                <title>Netflix</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/netflixSymbol.svg" />
            </Head>
            <BLogo movie={item} type={type} />

            <Cast id={item.id} type={type} />
            <Testimonials id={item.id} type={type} />
        </div>
    )
}
